import {FC} from 'react'

const Head: FC = () => {
  return (
    <>
      <title>NFT Marketplace</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by NFT Marketplace" />
    </>
  )
}

export default Head
