import {FC} from 'react'
import { Head } from 'next/document'

const head: FC = () => {
  return (
    <Head>
      <title>NFT Marketplace</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by NFT Marketplace" />
    </Head>
  )
}

export default head
